# Generated by Django 5.2.8 on 2025-11-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atmosphere",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("temp", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Buildings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("temp", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
