# Generated by Django 5.2.8 on 2025-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_app', '0002_device_delete_atmosphere_buildings_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
